services:
  api:
    build: .
    container_name: starwars_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: sqlite:////data/starwars.db
    volumes:
      - sqlite_data:/data
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]

  scheduler:
    build: .
    container_name: starwars_scheduler
    environment:
      DATABASE_URL: sqlite:////data/starwars.db
    volumes:
      - sqlite_data:/data
    command: ["python", "main.py"]

volumes:
  sqlite_data:
